spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/timeline?serverTimezone=CTT&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: xyw990331
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mybatis/*/*Mapper.xml
  type-aliases-package: com.sqlb.pojo
